### ISSUE TITLE
Unable to create AssetBundle

### ISSUE THREAD

**Issue by GoblinFiend** [HolographicWings/LethalSDK-Unity-Project#11]
![Capture](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/153674309/f55c2622-4f64-4434-a727-7ecbe200bade)

Hello! I love your mod btw and want to eventually be able to make a map. I was testing the SDK through Unity and have been trying to create a new scrap item. I believe I did everything correct but also I do not have much Unity experience. When I try to export the assetbundle I am met with an error. I've tried manually installing bepinex and lethalexpansion to see if that would fix the issue as opposed to using Thunderstore but no matter where I try to import the bundle to I still receive this error. If you could help guide me whatsoever it would be greatly appreciated!

**Comment by HolographicWings** [comment]
> ![Capture](https://private-user-images.githubusercontent.com/153674309/289987054-f55c2622-4f64-4434-a727-7ecbe200bade.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MTU1NTAsIm5iZiI6MTcwMjQxNTI1MCwicGF0aCI6Ii8xNTM2NzQzMDkvMjg5OTg3MDU0LWY1NWMyNjIyLTRmNjQtNDQzNC1hNzI3LTdlY2JlMjAwYmFkZS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQyMTA3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWRlYjY5ZWI1YWZmMzIwZmYwNmJiYzAxMzM5OWM1OWMwNWJkZTY5OWQ5NTYxYzRjOTc5OWYyZmViNGYwNTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F2DCrAHXRHO7ZGUxuH4f2m-qRlB2yRyROYUwKNuliCM)
> 
> Hello! I love your mod btw and want to eventually be able to make a map. I was testing the SDK through Unity and have been trying to create a new scrap item. I believe I did everything correct but also I do not have much Unity experience. When I try to export the assetbundle I am met with an error. I've tried manually installing bepinex and lethalexpansion to see if that would fix the issue as opposed to using Thunderstore but no matter where I try to import the bundle to I still receive this error. If you could help guide me whatsoever it would be greatly appreciated!

This issue happen because you have several assets of the same name, check every file and rename them if two of them have the same name

**Comment by GoblinFiend** [comment]
Thank you so much! It worked! I will be uploading my mod adding 1 new scrap item into the game later today after configuring some more option. You're the best for replying so fast.
