### ISSUE TITLE
AssetBundle corrupting LethalExpansion

### ISSUE THREAD

**Issue by GoblinFiend** [HolographicWings/LethalSDK-Unity-Project#13]
Hello, I was able to generate my assetbundle- but now when I load it into the game and start a server the entire LethalExpansion mod gets disabled. No new moons, no extra scrap items, etc. I am sure that it is my additional scrap item mod that is breaking LethalExpansion yet I don't know why as the only difference I see is the lack of the printout in the command prompt when creating the items and adding the moons. 

![Capture](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/153674309/b6f399ea-dd91-4b2e-865b-cda3c4685704)
^^ This is what it looks like with my personal trophy.lem assetbundle.

![Capture1](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/153674309/2d1f41e8-bf99-47e3-8eed-0696915694ed)
^^ This is what it looks like without my trophy.lem assetbundle.

I'll include the files below. Thanks in advance- I'm new to this and trying to get the hang of it.

**Comment by HolographicWings** [comment]
Hello @GoblinFiend 
I will take a look today

**Comment by GoblinFiend** [comment]
@HolographicWings 
Thanks <3

**Comment by HolographicWings** [comment]
> @HolographicWings Thanks <3

Can you send me the lem file too ?

**Comment by GoblinFiend** [comment]
@HolographicWings 
Thanks so much for your detailed response I'm working on some of these issues right now. I don't know where to find the scan node and apply it to my new item but other than that I've addressed all the other issues as of now. If possible a screenshot of the ScanNode element in the prefab would be great if possible!

**Comment by GoblinFiend** [comment]
> @HolographicWings Thanks so much for your detailed response I'm working on some of these issues right now. I don't know where to find the scan node and apply it to my new item but other than that I've addressed all the other issues as of now. If possible a screenshot of the ScanNode element in the prefab would be great if possible!

Nevermind, I found it. New to unity :p

**Comment by GoblinFiend** [comment]
@HolographicWings 
I just wanted to thank you for all the assistance once again. Everything now works and I am super happy with the result! It looks really good and works just as intended. , I have two more questions / concerns though. When holding the item it is sideways as opposed to right side up. How do I change this? 

Also, I would like to know more about the "weight" in the spawn chance. Can I weight it at .5? Is 100 the max weight? Some more clarity about how this system works would be great!

When looking at the item in the dark it also looks very dark almost black, which I imagine is because of the reflectivity of it. Do I need a normal map or something like: "Assets/Mods/TemplateMod/Items/Scraps/tape/survivaltools2_Tape_MetallicSmoothness.png"
To help remedy this?

You're amazing :D

**Comment by HolographicWings** [comment]
> @HolographicWings I just wanted to thank you for all the assistance once again. Everything now works and I am super happy with the result! It looks really good and works just as intended. I have some more questions / concerns though. When holding the item it is sideways as opposed to right side up. How do I change this?
> 
> Also, I would like to know more about the "weight" in the spawn chance. Can I weight it at .5? Is 100 the max weight? Some more clarity about how this system works would be great!
> 
> Other things: How do I find the name of the SFX? would it be DropBigBolt? When looking at the item in the dark it also looks very dark almost black, which I imagine is because of the reflectivity of it. Do I need a normal map or something like: "Assets/Mods/TemplateMod/Items/Scraps/tape/survivaltools2_Tape_MetallicSmoothness.png" To help remedy this?
> 
> You're amazing :D

It's the Offsets in the scrap
Theres a scene at Assets/Mods/LethalExpansion/Scenes/ItemPlaceTest.unity you can use it to place your scrap either on ItemHoldAxis or ItemGroundAxis, theses are references to rotate and scale your items corectly before set the offsets
