### ISSUE TITLE
v1.2.5 of LE broke

### ISSUE THREAD

**Issue by GoblinFiend** [HolographicWings/LethalSDK-Unity-Project#16]
It seems like LethalExpansion v1.2.5 is broken. I've tried uninstalling all mods and running only LethalExpansion (with Bepinex ofc) and am always getting the below error. When I revert to 1.2.4 it works.

![Capture](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/153674309/8016eb93-104d-44e2-9e8b-2a2acfb987ce)

**Comment by HolographicWings** [comment]
> It seems like LethalExpansion v1.2.5 is broken. I've tried uninstalling all mods and running only LethalExpansion (with Bepinex ofc) and am always getting the below error. When I revert to 1.2.4 it works.
> 
> ![Capture](https://private-user-images.githubusercontent.com/153674309/290645480-8016eb93-104d-44e2-9e8b-2a2acfb987ce.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1ODc4MDIsIm5iZiI6MTcwMjU4NzUwMiwicGF0aCI6Ii8xNTM2NzQzMDkvMjkwNjQ1NDgwLTgwMTZlYjkzLTEwNGQtNDRlMi05ZThiLTJhMmFjZmI5ODdjZS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQyMDU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2U3NWM0NDM3ZjUyYTc4MzY5ZDQwZTQ4NWRlNDgxMGYyODQ4MzZkYzM1ZDJmNzI1OTliODZmOTBhMDBmNThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.60AXtViAdqMYqzX-Z8P0jhtP8bZ_Ibuerss6g3Xeykc)

hello
same issue than here
https://github.com/HolographicWings/LethalExpansion/issues/12#issuecomment-1856504015
