### ISSUE TITLE
Suggestion: Change the Mesh Filter to something else

### ISSUE THREAD

**Issue by subzerohurley** [HolographicWings/LethalSDK-Unity-Project#17]
Was wondering if you can change the MeshFilter from only excepting raw meshes to allowing the whole model package? 
Asking because as it stands, I'd like to be able to add an armature for dynamic bones so my item can wobble (As I've seen someone do it with a glizzy) i apologies if my terminology is wrong, I'm still very new to Unity and dont know the names yet.
Of course if adding an Armature is possible atm I'd love to know!
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/18029175/3016466f-cfb6-45eb-bfcb-334e11d1e1eb)

**Comment by subzerohurley** [comment]
Learned what the root issue is, making a separate ticket

**Comment by HolographicWings** [comment]
> Was wondering if you can change the MeshFilter from only excepting raw meshes to allowing the whole model package? 
> Asking because as it stands, I'd like to be able to add an armature for dynamic bones so my item can wobble (As I've seen someone do it with a glizzy) i apologies if my terminology is wrong, I'm still very new to Unity and dont know the names yet.
> Of course if adding an Armature is possible atm I'd love to know!
> ![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/18029175/3016466f-cfb6-45eb-bfcb-334e11d1e1eb)
> 

You should be able to make more complexes prefabs while it have the proper components by following the templates
But C# don't have the security of Udon from VRChat, you can execute any code in a custom script so I can't allow this I'm sorry
I will maybe implement dynamic bones manually in the SDK in future
