### ISSUE TITLE
Scrap Pickup/Drop Sound help

### ISSUE THREAD

**Issue by subzerohurley** [HolographicWings/LethalSDK-Unity-Project#19]
Noticed this setting a while ago and figured you could add custom sounds for when you pick up and drop the scrap, however when I add my sound to this field, nothing happens?

![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/18029175/f13946fb-ce78-41c8-ac67-264963093c5a)

**Comment by HolographicWings** [comment]
> Noticed this setting a while ago and figured you could add custom sounds for when you pick up and drop the scrap, however when I add my sound to this field, nothing happens?
> 
> ![image](https://private-user-images.githubusercontent.com/18029175/290989118-f13946fb-ce78-41c8-ac67-264963093c5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjczMDEsIm5iZiI6MTcwMjcyNzAwMSwicGF0aCI6Ii8xODAyOTE3NS8yOTA5ODkxMTgtZjEzOTQ2ZmItY2U3OC00MWM4LWFjNjctMjY0OTYzMDkzYzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDExNDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YjAxNjcwZTg5ZDBiZTM5NDY4NWZmNTNmZTMwYWExMmQ5MWY1OTc0MmM3ZjAyNzJlNmRmMDgzZjFjMTU1NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e_miZWLZRf5bWSn1d3w-qwl5eXSwVSOMCRqS36EnxfI)

You have to register the sound in the asset bank of your module, see the manifest

**Comment by subzerohurley** [comment]
Will the SDK need to update too? or is 1.2.7 be fine still?

**Comment by HolographicWings** [comment]
> Will the SDK need to update too? or is 1.2.7 be fine still?

no SDK update

**Comment by subzerohurley** [comment]
Sweet! thank you! Everything's working smoothly!
