### ISSUE TITLE
Error when using AssetBundle Builder

### ISSUE THREAD

**Issue by Spooderman69** [HolographicWings/LethalSDK-Unity-Project#3]
I followed your writen tutorial as close as I could but I keep getting this error when I try to use the AssetBundle Builder.
After this error pops up Unity crashes. When I open the project again and try to use the AssetBundle Builder it doesn't work.
I hope you make a video tutorial soon. Or at least a visual tutorial.

[Worker0] Could not allocate memory: System out of memory!
Trying to allocate: 292057776131B with 16 alignment. MemoryLabel: String
Allocation happened at: Line:530 in C:\build\output\unity\unity\Runtime\Core\Containers\StringStorageDefault.h
Memory overview

[ ALLOC_TEMP_TLS ] used: 17307B | peak: 0B | reserved: 56950784B 
[ ALLOC_MEMORYPROFILER ] used: 660664B | peak: 1099152B | reserved: 2097152B 
[ ALLOC_DEFAULT ] used: 182111912B | peak: 0B | reserved: 218116096B 
[ ALLOC_TEMP_JOB_1_FRAME ] used: 0B | peak: 0B | reserved: 0B 
[ ALLOC_TEMP_JOB_2_FRAMES ] used: 0B | peak: 0B | reserved: 0B 
[ ALLOC_TEMP_JOB_4_FRAMES (JobTemp) ] used: 216302B | peak: 0B | reserved: 4194304B 
[ ALLOC_TEMP_JOB_ASYNC (Background) ] used: 0B | peak: 0B | reserved: 6291456B 
[ ALLOC_GFX ] used: 24613872B | peak: 0B | reserved: 50331648B 
[ ALLOC_CACHEOBJECTS ] used: 17188504B | peak: 0B | reserved: 117444608B 
[ ALLOC_TYPETREE ] used: 1640080B | peak: 0B | reserved: 8388608B 
[ ALLOC_PROFILER ] used: 629344B | peak: 630384B | reserved: 16777216B 
[ ALLOC_PROFILER_EDITOR ] used: 0B | peak: 0B | reserved: 0B 

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by HolographicWings** [comment]
> I followed your writen tutorial as close as I could but I keep getting this error when I try to use the AssetBundle Builder. After this error pops up Unity crashes. When I open the project again and try to use the AssetBundle Builder it doesn't work. I hope you make a video tutorial soon. Or at least a visual tutorial.
> 
> [Worker0] Could not allocate memory: System out of memory! Trying to allocate: 292057776131B with 16 alignment. MemoryLabel: String Allocation happened at: Line:530 in C:\build\output\unity\unity\Runtime\Core\Containers\StringStorageDefault.h Memory overview
> 
> [ ALLOC_TEMP_TLS ] used: 17307B | peak: 0B | reserved: 56950784B [ ALLOC_MEMORYPROFILER ] used: 660664B | peak: 1099152B | reserved: 2097152B [ ALLOC_DEFAULT ] used: 182111912B | peak: 0B | reserved: 218116096B [ ALLOC_TEMP_JOB_1_FRAME ] used: 0B | peak: 0B | reserved: 0B [ ALLOC_TEMP_JOB_2_FRAMES ] used: 0B | peak: 0B | reserved: 0B [ ALLOC_TEMP_JOB_4_FRAMES (JobTemp) ] used: 216302B | peak: 0B | reserved: 4194304B [ ALLOC_TEMP_JOB_ASYNC (Background) ] used: 0B | peak: 0B | reserved: 6291456B [ ALLOC_GFX ] used: 24613872B | peak: 0B | reserved: 50331648B [ ALLOC_CACHEOBJECTS ] used: 17188504B | peak: 0B | reserved: 117444608B [ ALLOC_TYPETREE ] used: 1640080B | peak: 0B | reserved: 8388608B [ ALLOC_PROFILER ] used: 629344B | peak: 630384B | reserved: 16777216B [ ALLOC_PROFILER_EDITOR ] used: 0B | peak: 0B | reserved: 0B
> 
> UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Hello, it was made with which version of the SDK ?
Can you give me more informations ? as a zip of your new mod folder, you can send me it by mail to HolographicWings@outlook.fr or here if you don't freak that someone steal it

It's late so i will investigate on the issue tomorrow

**Comment by Spooderman69** [comment]
Unity v2022.3.9
SDK v1.1.3
Ram 16Gb

I messed it up myself I tried again and it didnt crash, but it still didn't create an AssetBundle. I don't know if I am doing something wrong but I attached an error message I got. 

![Screenshot 2023-12-10 092122](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/75356901/8d79595e-4d27-40de-aac2-0e288f35c84e)

I changed the name of the copied TemplateMod folder to Test. I also change the Mod Name in the Mod Manifest to Test. Then I Build the AssenBundle using the Builder but nothing happened. It created the folder but it is empty.

![Screenshot 2023-12-10 092400](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/75356901/479318d8-1bf3-468d-911b-62ddcb60434a)

I am very new to all of this.

**Comment by HolographicWings** [comment]
> Unity v2022.3.9 SDK v1.1.3 Ram 16Gb
> 
> I messed it up myself I tried again and it didnt crash, but it still didn't create an AssetBundle. I don't know if I am doing something wrong but I attached an error message I got.
> 
> ![Screenshot 2023-12-10 092122](https://private-user-images.githubusercontent.com/75356901/289345866-8d79595e-4d27-40de-aac2-0e288f35c84e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTc2MzcsIm5iZiI6MTcwMjE5NzMzNywicGF0aCI6Ii83NTM1NjkwMS8yODkzNDU4NjYtOGQ3OTU5NWUtNGQyNy00MGRlLWFhYzItMGUyODhmMzVjODRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA4MzUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMDgxYjA5MTllZWE3ZmJjMWJjOWI0YzUzNjljMmVjZTUzNGJkNzI1YTNjNmMwN2E5YWZhZjIwNzU2NzU2YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-MdwmfrgJlNUW89mSQbfqAV7AAI8ybyHV_pGvyktRAE)
> 
> I changed the name of the copied TemplateMod folder to Test. I also change the Mod Name in the Mod Manifest to Test. Then I Build the AssenBundle using the Builder but nothing happened. It created the folder but it is empty.
> 
> ![Screenshot 2023-12-10 092400](https://private-user-images.githubusercontent.com/75356901/289345962-479318d8-1bf3-468d-911b-62ddcb60434a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTc2MzcsIm5iZiI6MTcwMjE5NzMzNywicGF0aCI6Ii83NTM1NjkwMS8yODkzNDU5NjItNDc5MzE4ZDgtMWJmMy00NjhkLTkxMWItNjJkZGNiNjA0MzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA4MzUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZWRkNmM1YWRhOGYxNjAzYjczMzE1MDM4ZDNlNjAyZjhhZmZlYmU1MmM3NjdjMWUwNDYxNDViMjY3NDkxYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pO214q0ty0F2KOeC-LRfpnvX0-cfvN7-iuxg3BszEpY)
> 
> I am very new to all of this.

yes i see the issue, you have to remove the Assets/Mods/LethalExpansion/Prefabs/Prefab.zip file and change the assetbundle of the scene at
Assets/Mods/LethalExpansion/Scenes/ItemPlaceTest.unity
to none
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/19623115/2c5590bb-fb51-492e-89d4-caad32c5f8d8)
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/19623115/7d907a6a-202e-45a9-b5ba-d34204c01fc9)

**Comment by Spooderman69** [comment]
I removed the .zip file. But the ItemPlaceTest.unity is already set to None and if I change the ItemPlaceTest folder to AssetBundle None, it changes it right back to lethalexpansion.

![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/75356901/c32f62cb-854b-4eeb-b549-2ef0df8fe119)
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/75356901/b85b70d8-2fdb-46dd-956f-861d7452a295)
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/75356901/7bcee3d8-1e8f-44a4-aec6-481b181bb4bf)

**Comment by epicduck64** [comment]
> I removed the .zip file. But the ItemPlaceTest.unity is already set to None and if I change the ItemPlaceTest folder to AssetBundle None, it changes it right back to lethalexpansion.
> 
> ![image](https://private-user-images.githubusercontent.com/75356901/289348058-c32f62cb-854b-4eeb-b549-2ef0df8fe119.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDE3MzIsIm5iZiI6MTcwMjIwMTQzMiwicGF0aCI6Ii83NTM1NjkwMS8yODkzNDgwNTgtYzMyZjYyY2ItODU0Yi00ZWViLWI1NDktMmVmMGRmOGZlMTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA5NDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZDFlYmFkZGI2ZTdiY2M3M2ZjNzUzYWRmNTc1YzFiMmYzMjk2NjBhYjQ3ZjZhMzUyZTZmYTRkNjFlOTFjOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nlh_fJbDDO7nl1MdFF5pRRWC3VJjYCCTXVoP4ICfDso) ![image](https://private-user-images.githubusercontent.com/75356901/289348088-b85b70d8-2fdb-46dd-956f-861d7452a295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDE3MzIsIm5iZiI6MTcwMjIwMTQzMiwicGF0aCI6Ii83NTM1NjkwMS8yODkzNDgwODgtYjg1YjcwZDgtMmZkYi00NmRkLTk1NmYtODYxZDc0NTJhMjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA5NDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZWJmM2RjMWMzODMxMjUyNDRmMWUyNDI3OGRiNThjNGNlMzA1Y2YyZGYwNDcxZDE1OGNkZGJiNjZiOWY4MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.syyuu2YEzDG36Tv_2vLyZrJ1z1tajg96SXH-OIVldtw) ![image](https://private-user-images.githubusercontent.com/75356901/289348107-7bcee3d8-1e8f-44a4-aec6-481b181bb4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDE3MzIsIm5iZiI6MTcwMjIwMTQzMiwicGF0aCI6Ii83NTM1NjkwMS8yODkzNDgxMDctN2JjZWUzZDgtMWU4Zi00NGE0LWFlYzYtNDgxYjE4MWJiNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA5NDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NDM5N2Y0ZTk0NTNjMzc1ODU5M2JkZTk2MzhkYTIzNWY4YzY1NjUzMTIwMDUxYWQ3OTA2NzY5NzNjYjU1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mkS1QqaIpwOFtUYHm9d6jv3I_jZBchhTuqcBR6n5f60)

Found success in deleting my project, loading up a fresh copy of the project, NOT building assetbundles yet, following the steps recommended by creator (removing scene from AB and deleting Prefabs.zip), then building assetbundle fixed my problem. I just deleted the entire scenes folder from LethalExpansion since it didn't have anything important anyways, even though the scene wasn't included with the AB anyways.
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/39019028/9d3e79db-1b42-433b-8a89-efea5cc3d272)

**Comment by HolographicWings** [comment]
> > I removed the .zip file. But the ItemPlaceTest.unity is already set to None and if I change the ItemPlaceTest folder to AssetBundle None, it changes it right back to lethalexpansion.
> > ![image](https://private-user-images.githubusercontent.com/75356901/289348058-c32f62cb-854b-4eeb-b549-2ef0df8fe119.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDE3MzIsIm5iZiI6MTcwMjIwMTQzMiwicGF0aCI6Ii83NTM1NjkwMS8yODkzNDgwNTgtYzMyZjYyY2ItODU0Yi00ZWViLWI1NDktMmVmMGRmOGZlMTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA5NDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZDFlYmFkZGI2ZTdiY2M3M2ZjNzUzYWRmNTc1YzFiMmYzMjk2NjBhYjQ3ZjZhMzUyZTZmYTRkNjFlOTFjOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nlh_fJbDDO7nl1MdFF5pRRWC3VJjYCCTXVoP4ICfDso) ![image](https://private-user-images.githubusercontent.com/75356901/289348088-b85b70d8-2fdb-46dd-956f-861d7452a295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDE3MzIsIm5iZiI6MTcwMjIwMTQzMiwicGF0aCI6Ii83NTM1NjkwMS8yODkzNDgwODgtYjg1YjcwZDgtMmZkYi00NmRkLTk1NmYtODYxZDc0NTJhMjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA5NDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZWJmM2RjMWMzODMxMjUyNDRmMWUyNDI3OGRiNThjNGNlMzA1Y2YyZGYwNDcxZDE1OGNkZGJiNjZiOWY4MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.syyuu2YEzDG36Tv_2vLyZrJ1z1tajg96SXH-OIVldtw) ![image](https://private-user-images.githubusercontent.com/75356901/289348107-7bcee3d8-1e8f-44a4-aec6-481b181bb4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDE3MzIsIm5iZiI6MTcwMjIwMTQzMiwicGF0aCI6Ii83NTM1NjkwMS8yODkzNDgxMDctN2JjZWUzZDgtMWU4Zi00NGE0LWFlYzYtNDgxYjE4MWJiNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA5NDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NDM5N2Y0ZTk0NTNjMzc1ODU5M2JkZTk2MzhkYTIzNWY4YzY1NjUzMTIwMDUxYWQ3OTA2NzY5NzNjYjU1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mkS1QqaIpwOFtUYHm9d6jv3I_jZBchhTuqcBR6n5f60)
> 
> Found success in deleting my project, loading up a fresh copy of the project, NOT building assetbundles yet, following the steps recommended by creator (removing scene from AB and deleting Prefabs.zip), then building assetbundle fixed my problem. I just deleted the entire scenes folder from LethalExpansion since it didn't have anything important anyways, even though the scene wasn't included with the AB anyways. ![image](https://private-user-images.githubusercontent.com/39019028/289350819-9d3e79db-1b42-433b-8a89-efea5cc3d272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDkwNTYsIm5iZiI6MTcwMjIwODc1NiwicGF0aCI6Ii8zOTAxOTAyOC8yODkzNTA4MTktOWQzZTc5ZGItMWI0Mi00MzNiLThhODktZWZlYTVjYzNkMjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDExNDU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OGZlZGM3NmU5NDNkZmY2ZGY1ODQwZTg0ZDYxYTZkYjZkMDYyNDI0NzVhMjc5NTljM2YwNDMzNmNjYjFjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.65fAQdF3i1UnYaMlrQrQBPdNX_kl0tyvQY9uoJGX9bE)
> 
> Essentially, building the AB at all when there is Prefabs.zip for some reason completely bricks your project, making you have to start over.

Remove the Scenes folder if it continues then
I fixed the issue for the next update
Thanks for reporting
