### ISSUE TITLE
Is it possible to add my own SFX to the scrap items?

### ISSUE THREAD

**Issue by LoLoFoSt** [HolographicWings/LethalSDK-Unity-Project#32]
Hey! I've made some scrap items and would like to give them all custom sounds of grabbing and dropping, without using any of the sounds that are already in-game. Is it possible to do so and how?

**Comment by HolographicWings** [comment]
> Hey! I've made some scrap items and would like to give them all custom sounds of grabbing and dropping, without using any of the sounds that are already in-game. Is it possible to do so and how?

Yes
The assetbank is made for it

**Comment by Joshi120** [comment]
Greetings, i am very sorry to comment on this closed section, but i feel like i am either stupid or something isn't working "doubt that's the case" i added a sound inside the AssetBank , "the one that is there by default and already linked to the Manifest. But ingame it's just the default sound when you drop it or pick it up.... i must be doing something Very wrong
