### ISSUE TITLE
Possible to have Scrap animated?

### ISSUE THREAD

**Issue by NasbyCroco** [HolographicWings/LethalSDK-Unity-Project#34]
I created my own scrap. My cubodile mascot (square crocodile)

I first tested the item with it spawning in with it scannable and its own squeak pickup and drop sound effect.
Then I added a sound file that plays, similar to toy robot or chattering teeth, which works.
Now when I added an animation to the cubodile scrap item it completely disappears.
Doesn't load at all into the level.

So is there a specific script or prefab setup I need to animate the object?
I want it to rock back and forth slightly and also a little squishing (kinda rubber hose animation like)
![cubo](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/154874396/ee993423-3909-4132-8f13-f02e9c00534d)

### **EDIT**
I found a way to animate it and it to appear in the game correctly!

**Comment by HolographicWings** [comment]
> I created my own scrap. My cubodile mascot (square crocodile)
> 
> I first tested the item with it spawning in with it scannable and its own squeak pickup and drop sound effect.
> Then I added a sound file that plays, similar to toy robot or chattering teeth, which works.
> Now when I added an animation to the cubodile scrap item it completely disappears.
> Doesn't load at all into the level.
> 
> So is there a specific script or prefab setup I need to animate the object?
> I want it to rock back and forth slightly and also a little squishing (kinda rubber hose animation like)
> ![cubo](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/154874396/ee993423-3909-4132-8f13-f02e9c00534d)
> 
> 
> ### **EDIT**
> I found a way to animate it and it to appear in the game correctly!
> 

Yes, you can just add an animation controller to your scrap ^^
