### ISSUE TITLE
Can't pick up items

### ISSUE THREAD

**Issue by Moorio69** [HolographicWings/LethalSDK-Unity-Project#44]
For some reason I'm unable to pick up any of the custom scrap. It is possible to scan them and the grab icon shows up when I look at them but nothing happens when I press E. How could I fix this? There aren't any guides to follow, or at least none that I can find, and the instructions on github doesn't help.

**Comment by HolographicWings** [comment]
> For some reason I'm unable to pick up any of the custom scrap. It is possible to scan them and the grab icon shows up when I look at them but nothing happens when I press E. How could I fix this? There aren't any guides to follow, or at least none that I can find, and the instructions on github doesn't help.

logs please

**Comment by Moorio69** [comment]
I managed to fix it. Can't really remember how but i think it was that i forgot to resize the box collider or that it was placed on the wrong thing. Sorry to bother🙌
