### ISSUE TITLE
Project carry over

### ISSUE THREAD

**Issue by Kimmienin** [HolographicWings/LethalSDK-Unity-Project#48]
Hello, 

I was seeing if there was a way to carry over my current file project to the new update. First time modding and using unity so wasn't sure how to carry a current project file I'm working on to the latest LethalSDK update.

**Comment by HolographicWings** [comment]
> Hello, 
> 
> I was seeing if there was a way to carry over my current file project to the new update. First time modding and using unity so wasn't sure how to carry a current project file I'm working on to the latest LethalSDK update. 

Just drop the new update on it ane overwrite
Beware, it will overwrite the scenebuilder so save your prefabs
