### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by L-Vi** [HolographicWings/LethalSDK-Unity-Project#49]
Hey HolographicWings.  Great work on this so far.  Unity project is well put together and it didn't take me long at all to figure out how most of it fits together.  

Few queries though:

1 - I'd like to understand a little more about your asset bundling process.  Are you cycling through the whole project, or specific folders?  I just want to make sure I don't accidentally bundle 3rd party tools / unused assets.  

2 - Any idea what's causing this error while bundling?  
Two properties with the same reference name (_DoubleSidedEnable) using different types
UnityEditor.BuildPipeline:BuildAssetBundles (string,UnityEditor.BuildAssetBundleOptions,UnityEditor.BuildTarget)
LethalSDK.Editor.Lethal_AssetBundleBuilderWindow:BuildAssetBundles ()

3 - What exactly are Outdoor Nodes?  This is the one item I haven't been able to identify.

4 - I have the itemshipinstancer in it's template project default position.  However in game, it is spawning somewhere else and I have no idea where. I hear it somewhere in the distance, possibly very high on the Y axis.  Any insights you can provide on this?

And also one suggestion:
For future users, please make it more clear that the audio reverb presets are also responsible for changing weather and effects.  Took me a good while to figure out that those triggers were what I needed to be using.

**Comment by HolographicWings** [comment]
> Hey HolographicWings. Great work on this so far. Unity project is well put together and it didn't take me long at all to figure out how most of it fits together.
> 
> Few queries though:
> 
> 1 - I'd like to understand a little more about your asset bundling process. Are you cycling through the whole project, or specific folders? I just want to make sure I don't accidentally bundle 3rd party tools / unused assets.

it bundle the folders that are in Assets/Mods each independantly

> 2 - Any idea what's causing this error while bundling? Two properties with the same reference name (_DoubleSidedEnable) using different types UnityEditor.BuildPipeline:BuildAssetBundles (string,UnityEditor.BuildAssetBundleOptions,UnityEditor.BuildTarget) LethalSDK.Editor.Lethal_AssetBundleBuilderWindow:BuildAssetBundles ()

First time i see it, sometimes restart unity is enough, otherwise check if you don't have a conflict in file names, two files can't have the same names

> 3 - What exactly are Outdoor Nodes? This is the one item I haven't been able to identify.

OutsideNodes are the spawn spots for everything that are random outside

> 4 - I have the itemshipinstancer in it's template project default position. However in game, it is spawning somewhere else and I have no idea where. I hear it somewhere in the distance, possibly very high on the Y axis. Any insights you can provide on this?

Tell me more, send me screenshots of the instancer in your project

> And also one suggestion: For future users, please make it more clear that the audio reverb presets are also responsible for changing weather and effects. Took me a good while to figure out that those triggers were what I needed to be using.

I may warn it yes, but i don't want to rename the classes, they are ported into the vanilla ones with the same name

**Comment by HolographicWings** [comment]
> Thanks for the fast response.
> 
> > > 2 - Any idea what's causing this error while bundling? Two properties with the same reference name (_DoubleSidedEnable) using different types UnityEditor.BuildPipeline:BuildAssetBundles (string,UnityEditor.BuildAssetBundleOptions,UnityEditor.BuildTarget) LethalSDK.Editor.Lethal_AssetBundleBuilderWindow:BuildAssetBundles ()
> > 
> > First time i see it, sometimes restart unity is enough, otherwise check if you don't have a conflict in file names, two files can't have the same names
> 
> Unfortunately no restarting unity does nothing.  _DoubleSidedEnabled is clearly a material property ... probably flora materials.  I'll have to try removing assets until I can narrow it down.  This is another reason why I wanted to understand what is actually happening in the bundling process.
> 
> > Tell me more, send me screenshots of the instancer in your project.
> 
> Attached.  I've also tried adding it to the scene from the prefabs, bringing in a duplicate of the systems gameobject directly from the TemplateMod, and reimporting the project files from your zip.  I'm going to be missing something really obvious, I just can't seem to pinpoint it.
> 
> > I may warn it yes, but i don't want to rename the classes, they are ported into the vanilla ones with the same name
> 
> Fair one.
> 
> 
> ![itemship-shot](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/65398704/4141e817-4147-419f-a193-151b6af1099d)
> ![itemship-heirarchy](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/65398704/39a9ac0d-82eb-4338-a95c-4a0f62628acf)
> ![itemship-root-cursed1](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/65398704/551eecdc-dafe-43da-961f-fae9ddbc46c5)
> ![itemship-systems](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/65398704/e8703ac6-540e-4c66-9a98-5209981a7f25)
> ![itemship-instancer](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/65398704/e80f9311-b718-4cfc-ab6e-8dd7537fe820)
> 
> 
> 

Can you find where it spawn in game with the Unity Explorer ?

**Comment by L-Vi** [comment]
Unity Explorer was a good shout.  (in seven years of Unity, how did I not know about this?) 

Dropship solved.  And good news is that it seems to be my fault and not a bug.
  - I found there were two item ships instantiating. 
  - The first would instantiate after confirming the moon via the terminal (with a transform that was off map).
  - The second would instantiate after pulling the lever to start the game (with the correct transform).
  - Not *entirely* sure how I fixed it, but I think it came down to redefining my object names to be more specific, and then updating the ScriptableObjects to match the new names.  (there was certainly only one item ship in the prefab).

I'll update when I find the answer to the double sided issue.

**Comment by HolographicWings** [comment]
> 2 - Any idea what's causing this error while bundling?  
> Two properties with the same reference name (_DoubleSidedEnable) using different types
> UnityEditor.BuildPipeline:BuildAssetBundles (string,UnityEditor.BuildAssetBundleOptions,UnityEditor.BuildTarget)
> LethalSDK.Editor.Lethal_AssetBundleBuilderWindow:BuildAssetBundles ()
> 

Check if you don't have two times the same shader
If a "double sided" property is used two times by different types it may be a shader conflict

**Comment by HolographicWings** [comment]
> I'm going to close this out as the errors have mysteriously stopped appearing. While I still don't know the cause, I do not believe the issue is related to your project. Many thanks for your help.

Welcome to Unity xD

**Comment by HolographicWings** [comment]
> I'm going to close this out as the errors have mysteriously stopped appearing. While I still don't know the cause, I do not believe the issue is related to your project. Many thanks for your help.

Unity be like xD
