### ISSUE TITLE
Is HDRP intentional?

### ISSUE THREAD

**Issue by muzzletgh** [HolographicWings/LethalSDK-Unity-Project#58]
Every time I load up the project in Unity it loads in HDRP, making all of the objects invisible.

**Comment by muzzletgh** [comment]
The scene is invisible as a whole until I delete the entire settings folder

**Comment by muzzletgh** [comment]
Figured it out.

**Comment by HolographicWings** [comment]
> Figured it out.

The game is HDRP
If you don't use the project with HDRP you will have issues when importing your scraps and moons
