### ISSUE TITLE
Scrap value not aligning with Min and Max values.

### ISSUE THREAD

**Issue by verosment** [HolographicWings/LethalSDK-Unity-Project#6]
Hi, I've been toying around with this and have been trying to add a metronome scrap as a test, but it seems like the value doesn't match up with the 'Min Value' and 'Max Value' I've set in the Unity editor. The Min value is set to 60 and the Max is set to 85, meaning the value should be within this range. But as you can see in the screenshots, it does not stay within the 60-85 value. 

How can I make sure that the scrap's value will stay between these two numbers, is there something I can do on my end or is this a bug?

### Screenshots:
![Screenshot 2023-12-11 183845](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/64132923/51eac616-a9fa-45f8-a06a-bd6596d0ee99)
![Screenshot 2023-12-11 184124](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/64132923/22fca760-ab81-47c4-8cff-f8f440c7599c)
![Screenshot 2023-12-11 184238](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/64132923/771592cf-d244-47e3-89f8-4da1acc35d07)

**Comment by HolographicWings** [comment]
> Hi, I've been toying around with this and have been trying to add a metronome scrap as a test, but it seems like the value doesn't match up with the 'Min Value' and 'Max Value' I've set in the Unity editor. The Min value is set to 60 and the Max is set to 85, meaning the value should be within this range. But as you can see in the screenshots, it does not stay within the 60-85 value.
> 
> How can I make sure that the scrap's value will stay between these two numbers, is there something I can do on my end or is this a bug?
> 
> ### Screenshots:
> ![Screenshot 2023-12-11 183845](https://private-user-images.githubusercontent.com/64132923/289512088-51eac616-a9fa-45f8-a06a-bd6596d0ee99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDc3MzIsIm5iZiI6MTcwMjMwNzQzMiwicGF0aCI6Ii82NDEzMjkyMy8yODk1MTIwODgtNTFlYWM2MTYtYTlmYS00NWY4LWEwNmEtYmQ2NTk2ZDBlZTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE1MTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOTZkZjRhNzRjNGE0MTdmNzA3OWRjYWYyOWZkMWQ5M2MzM2Y0NDkyOWQ4NmZiNmNhOTcwNzJiOTY1Y2MwZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pCM_-Jen4xcDzlAWUNSSGVdpS35A3aGsjew6f-MfS4k) ![Screenshot 2023-12-11 184124](https://private-user-images.githubusercontent.com/64132923/289512107-22fca760-ab81-47c4-8cff-f8f440c7599c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDc3MzIsIm5iZiI6MTcwMjMwNzQzMiwicGF0aCI6Ii82NDEzMjkyMy8yODk1MTIxMDctMjJmY2E3NjAtYWI4MS00N2M0LThjZmYtZjhmNDQwYzc1OTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE1MTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MzFlYzEzNjM1NjA5OGIyNjExYTQ1YmY4Y2NkMDQ5ZGE2YmZkMGM0NzBkOWNhMmJiYTJjNjFiZTViZWE2YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N1G1MDymHs8yiDY3klQZmfkn4CdTW49QWe0vBgadP_U) ![Screenshot 2023-12-11 184238](https://private-user-images.githubusercontent.com/64132923/289512123-771592cf-d244-47e3-89f8-4da1acc35d07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDc3MzIsIm5iZiI6MTcwMjMwNzQzMiwicGF0aCI6Ii82NDEzMjkyMy8yODk1MTIxMjMtNzcxNTkyY2YtZDI0NC00N2UzLTg5ZjgtNGRhMWFjYzM1ZDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE1MTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljY2UwNGU2ZGJkOTY4YjZiZjUyOTliMDljMmU1MjVlYmQ4N2NlNjAyZTk3NzcyMWVmODI1ZTI3M2U0Y2U0MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DNkcCaCya5NBrCQ763k5j76FF7s_plscI2jik5ziksE)

Hello it's not a bug, in vanilla all scraps have 0.4x of their value, you can change it in the settings menu
it's why the Apparatus is 80 and not 200 as it is supposed to be

**Comment by verosment** [comment]
Ooh, that makes sense. I didn't know that before now, thank you!
