### ISSUE TITLE
Enemies, instead of patrolling the map, go to zero coordinates and get stuck.

### ISSUE THREAD

**Issue by RazrabGit** [HolographicWings/LethalSDK-Unity-Project#65]
There is a problem: my enemies are moving strangely around the map. Nav mesh is there, OutsideNode is too, but the enemies don’t want to patrol the map, but go to zero coordinates and stand still. Moreover, if you disturb them, they will chase you. Did I do something wrong?

**Comment by Wesley-wasnietavailabledusdanmaarzo** [comment]
I had this issue with Infernis for a while, not quite sure how I fixed it but it was defnitely something I did wrong.
You'll have to do some testing.

**Comment by RazrabGit** [comment]
I found the reason. You need to move the OutsideNodes towards you halfway so that it does not come into contact with its collision. Then everything will work.
