### ISSUE TITLE
Custom Scraps aren't able to pickup

### ISSUE THREAD

**Issue by ZombieKingJD** [HolographicWings/LethalSDK-Unity-Project#70]
Im having issues with being able to pick up my custom items.I am able to scan the item just no option to pickup. Not sure if its me or the scrap  i made, Any help would be awesome!
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/156404304/73eb093d-2d8b-4890-8dd3-118450b074b3)
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/156404304/9af71f45-b162-46af-ada7-61b4829eed8c)
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/156404304/054319e6-c73f-4e14-8046-09d4fbab1548)

 please let me know if you need any more screenshots

**Comment by HolographicWings** [comment]
Did you placed a box collider on it ?

**Comment by ZombieKingJD** [comment]
yes i have a box collider on both the mesh and the  Scan Node

**Comment by ZombieKingJD** [comment]
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/156404304/0f1f77e8-b6ba-4a4c-9f77-8ba863eeab5b)
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/156404304/6256862b-8d2a-451d-a940-1367a6ee8d7b)

**Comment by HolographicWings** [comment]
The tag and layer are not good, look at the templates

**Comment by ZombieKingJD** [comment]
Ohh i see, thank you very much @HolographicWings i completely forgot about that
