### ISSUE TITLE
I have a error when a try to make the assetBundle

### ISSUE THREAD

**Issue by JusteLoneWolf** [HolographicWings/LethalSDK-Unity-Project#74]
Hi !  yesterday i have this error when i try to make a asset bundles
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/36123003/80944f26-6ef9-491b-b7e0-57178b47c18e)

I'm trying to redo the project but I keep getting this error, anyone have a idea ? 

The logs
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/36123003/a37ccddd-0eed-4f2a-bc6b-66e9bb235c77)

**Comment by JusteLoneWolf** [comment]
Fixed, the material have the same name with another material, mb

**Comment by HolographicWings** [comment]
yet, it's a file name conflict
