### ISSUE TITLE
Moon cannot be added, "missing or incompatible bundles"

### ISSUE THREAD

**Issue by ThatonePanMan** [HolographicWings/LethalSDK-Unity-Project#75]
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/157259292/82eee0e0-8193-4175-b77f-c2136d9795d7)

My custom moon is being detected, but it's not being added because of "missing or incompatible bundles"
I don't think anything is incompatible and I have LethalExpansion installed in my test modpack, so what am I missing here??

![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/157259292/95f70a86-99d0-4ef7-ad59-98f914c94293)

**Comment by HolographicWings** [comment]
Look at the mod manifest of your mod
Theres a requirement field

**Comment by ThatonePanMan** [comment]
yup, just checked the manifest in notepad, I'll dive back into the project and fix that

**Comment by ThatonePanMan** [comment]
ok, still getting the same error message despite removing the need for the template .lem, having the .lem with the assets I need, and having the lethalexpansion.lem in the plugins
and I don't have anything on the incompatible bundles list, so what, do I need to just shove the folder with all the assets into the mod folder in the project?

**Comment by HolographicWings** [comment]
show me a screenshot your manifest

**Comment by ThatonePanMan** [comment]
it's still happening, I get the same error, despite having bbh.lem in the mod folder
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/157259292/d9040679-6292-472f-b078-75239ac3831f)
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/157259292/8299d53d-b414-41c8-abfc-4ed235819a22)

**Comment by ThatonePanMan** [comment]
ok, I got it to work by just putting all the assets into the folder with all the moon info and removing the required bundles from the list
