### ISSUE TITLE
AssetBank Audio not working

### ISSUE THREAD

**Issue by Joshi120** [HolographicWings/LethalSDK-Unity-Project#76]
Greetings, i feel like i am either stupid or something isn't working "doubt that's the case" i added a sound inside the AssetBank , "the one that is there by default and already linked to the Manifest. But in-game it's just the default sound when you drop it or pick it up.... i must be doing something Very wrong

**Comment by CidFexon** [comment]
After adding your sound to the assetBank you have to go to the inspector of your scrap and you just add the name of your audio.

like : 
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/159256463/b1eee85f-f20d-4d6d-b3e9-e84afa793232)
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/159256463/5328cea5-3838-4a65-88cf-c73e504bcb63)

**Comment by HolographicWings** [comment]
Thanks @CidFexon for answered before me ❤️ 
Yes, the asset bank just register the audio in game, you still need to define it in the scrap
By default if you put no name for the sound, it will take the filename

**Comment by Joshi120** [comment]
Thanks for the Reply, but i forgot to say i already did that. Buuut.... it was infact me being stupid. it was a simple upper and lowercase error on my side, Thanks tho! :)
