### ISSUE TITLE
audio problem, I would like to set a time limit on the use of my "airhorn/clownhorn"

### ISSUE THREAD

**Issue by CidFexon** [HolographicWings/LethalSDK-Unity-Project#77]
Hello, I need help with the sound of my scrap, when I or someone uses it you can activate it endlessly, the problem is that the sound starts again every time we activate it and it quickly becomes deaf to hear.

is there a way to fix it?

I thank you in advance.

**Comment by HolographicWings** [comment]
To be honest i don't know, i simply port the fields to make the scrap work as an airhorn, i haven't looked at the code of the airhorn at all.
Nobody else reported me this issue, so it may be from the encoding of your audio file ? I dunno really

**Comment by CidFexon** [comment]
I wouldn't be able to say the encoding of my audio file, to be honest I'm just implanting files. 

Could you tell me what encoding is used for the airhorn? I looked on the internet and I admit I'm a little lost with all these types of encoding, should it be done in a separate software? or can I do it directly on unity?

**Comment by HolographicWings** [comment]
> I wouldn't be able to say the encoding of my audio file, to be honest I'm just implanting files.
> 
> Could you tell me what encoding is used for the airhorn? I looked on the internet and I admit I'm a little lost with all these types of encoding, should it be done in a separate software? or can I do it directly on unity?

I really dunno, all a think is that bad encoring may not be read properly by unity
or maybe i tell shit

**Comment by CidFexon** [comment]
my level of use of unity is very basic, the only thing I think that could solve the problem is at the coding level, by putting a sound activation delay. The sound I used is from a game so I don't think the encoding is a problem (.ogg), the sound works well in the game but restarts with each click and therefore accumulates. Is it possible to modify the sdk modpack code?

**Comment by HolographicWings** [comment]
> my level of use of unity is very basic, the only thing I think that could solve the problem is at the coding level, by putting a sound activation delay. The sound I used is from a game so I don't think the encoding is a problem (.ogg), the sound works well in the game but restarts with each click and therefore accumulates. Is it possible to modify the sdk modpack code?

Modify it for what ? The SDK is just porting the fields to the vanilla classes.
Try with any other sound, use a vanilla sound like "GrabFlashlight" and tell me if that still happen

**Comment by CidFexon** [comment]
I tried to add a classic sound, the grab and even the clownhorn, but it always does the same thing, if you don't spam it works very well, but if I click several times the sound starts again while keeping the old one so This is becoming horrible to hear. I'll send you a video of what it does, then if you don't know where it could come from it's not too serious, I'll try to get by by scratching everywhere, otherwise I'll use another mod to add the sound if it works.

video like : https://youtu.be/Yr1YFndfjwM

**Comment by HolographicWings** [comment]
As i said, try with GrabFlashlight as sound and tell me if you can spam it please

**Comment by CidFexon** [comment]
sorry I explained myself badly, I tested with the grabflashlight and it does the same thing, I even tried putting "clownhorn" it does the same thing to me. 

video like : https://www.youtube.com/watch?v=ABHGuYx_39w

The only solution I imagined is to create an external dll with an "if" which analyzes each item, finds my items and creates a cooldown via the harmony library

**Comment by CidFexon** [comment]
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/159256463/0f4bcf21-b02e-4d7a-bae8-1528b2a09334)

**Comment by HolographicWings** [comment]
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/19623115/b2cf23ec-fc88-4c64-b274-fe1dd549739b)
i may try to add this field in next update

**Comment by HolographicWings** [comment]
Added in 1.3.41 of the SDK, tell me if it fixes the issue

**Comment by CidFexon** [comment]
I just tried to modify the cooldown float but it doesn't seem to want to change, I did as a test: 0 / 1 / 10 / 100 / 5000 but none of these numbers changed :c

**Comment by HolographicWings** [comment]
Did you used both LE and the SDK 1.3.41 ? the mod need to be updated too

**Comment by CidFexon** [comment]
oh my god, I'm stupid, it was the problem with the lethal expansion version, thank you for helping me with this problem, everything works fine, there is a delay !!

THANK YOU SO MUCH
