### ISSUE TITLE
Created AssetBundle is extremely large (~15mb of assets->283mb bundle)

### ISSUE THREAD

**Issue by andymwat** [HolographicWings/LethalSDK-Unity-Project#78]
I'm working on a simple mod that adds a few items of scrap. I've noticed that as I've added items, the size of the generated AssetBundle has grown much faster than the size of the actual assets. My mod currently contains about 15 mb of assets, but the generated AssetBundle has reached 283mb.

I've been following the [mod setup guide](https://github.com/BuffMage/LethalExpansionGuides/blob/main/ModSetup.md) and [normal scrap guide](https://github.com/BuffMage/LethalExpansionGuides/blob/main/ScrapGuides/NormalScrapType.md).

Mod Assets folder:
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/42820057/1be4fd40-0d7c-4c3d-8f98-1e4491e73173)

Generated AssetBundle file:
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/42820057/b550e948-bdef-43f8-98d1-6b11f270e882)

Loading both the generated templatemod asset bundle file and the file for my own mod in the [Unity Asset Bundle Viewer](https://github.com/Unity-Technologies/AssetBundles-Browser), the only thing I can tell that's different is that the templatemod asset bundle lists the lethalexpansion.lem file as a dependency, while my own mod does not.

AssetBundle viewed in the Asset Bundle Browser:
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/42820057/f933cdcd-90d7-4e4a-98b6-f347d47c31ce)

My mod's .lem file details:
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/42820057/77ed45ef-0897-4d36-bdbe-3f86c7907259)

templatemod.lem file details:
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/42820057/83d0c79c-032d-49ca-82fb-dd49dc612bce)

**Comment by andymwat** [comment]
I uploaded it to DropBox here: https://www.dropbox.com/scl/fi/2v18mvjj3h8akzd7t4zfj/umacompany.lem?rlkey=gtpvzcq100aa2ufhj22x7jwzu&dl=0

**Comment by HolographicWings** [comment]
After unpacked the LEM
umacompany\items\scraps\mirako\Body.004.asset is 823 MB
umacompany\items\scraps\riceshower\Body.asset is 657 MB
umacompany\items\scraps\digital\Body.asset is 922 MB
look at theses files, they may grow for a reason, i dunno personally

**Comment by andymwat** [comment]
I think I've figured it out. I created a new mod that was empty except for a single imported .fbx model. It was ~40mb until I disabled "Import BlendShapes" on the mesh's import settings. After that box was unchecked, the exported file was just 700kb. 

Also, what tool did you use to unpack the LEM? I'd be interested in taking a look at it.

**Comment by HolographicWings** [comment]
> I think I've figured it out. I created a new mod that was empty except for a single imported .fbx model. It was ~40mb until I disabled "Import BlendShapes" on the mesh's import settings. After that box was unchecked, the exported file was just 700kb. 
> 
> Also, what tool did you use to unpack the LEM? I'd be interested in taking a look at it.

Unity Asset Ripper
