### ISSUE TITLE
spawn scrap outside?

### ISSUE THREAD

**Issue by StyledSnail** [HolographicWings/LethalSDK-Unity-Project#8]
is it possible to spawn scrap on the surface?

**Comment by HolographicWings** [comment]
> is it possible to spawn scrap on the surface?

unfortunately not
the only way is to spawn it as Spawnable Outside Objects, but it seems to don't work so i must check about it
i have too much things to fix or add for now, i will leave this in secondary priority if you don't mind ^^

**Comment by StyledSnail** [comment]
alright, understandable, have a great day
