### ISSUE TITLE
Moons

### ISSUE THREAD

**Issue by hiitsmike1** [HolographicWings/LethalSDK-Unity-Project#9]
The moons do not load for me at all. When I launch the game, I see the mod settings but in the terminal both the moons aren't there. Is this an issue on my end? I downloaded both this mod and the lethalSDK mod straight off of thunderstore. and when I run it, only the vanilla moons are in the terminal.

**Comment by HolographicWings** [comment]
Hello
Can you show me your lots ?

**Comment by hiitsmike1** [comment]
I tried loading it with only lethal expansion and the moons still don’t show up. There are no errors other than it saying it is trying to call on a different version of bepinEx (5.4.22) when the most updated I can find it 5.4.21. It also says that it already loaded the maps when trying to load the assets.

**Comment by HolographicWings** [comment]
> I tried loading it with only lethal expansion and the moons still don’t show up. There are no errors other than it saying it is trying to call on a different version of bepinEx (5.4.22) when the most updated I can find it 5.4.21. It also says that it already loaded the maps when trying to load the assets.

BepInEx version is not an issue, i built the mod with 5.4.22 but that break nothing.
"Already loaded" is from LC_API ? If yes, i sent a compatibility patch to the LC_API's dev, waiting for answer.

But i need more informations, i can't help you without details
Like full logs and a screenshot of the terminal

**Comment by hiitsmike1** [comment]
![image_2023-12-13_152506131](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/153572285/30564dd7-3999-4b21-9071-d58d0199fc09)
Its showing this whenever I open my game and I only have Lethal Expansion and BepinEx Downloaded straight from the thunderstore

**Comment by HolographicWings** [comment]
> ![image_2023-12-13_152506131](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/153572285/30564dd7-3999-4b21-9071-d58d0199fc09)
> Its showing this whenever I open my game and I only have Lethal Expansion and BepinEx Downloaded straight from the thunderstore

This message means you have two times the same modules installed
Uninstall the expansion mod, check everywhere to remove the remaining .lem files either in the R2Modman profile folder and the bepinex plugins folder in the game directory if exist
When reinstalled the expansion, send me a screenshot of the moon catalogue in your terminal

**Comment by hiitsmike1** [comment]
I finally got it to work. Thank you!
